### ISSUE TITLE
Question about any expansion plans for this project.

### ISSUE THREAD

**Issue by sylvanr** [codeforIATI/imf-exchangerates#1]
Hi guys,

Really impressive work here, coming over from the Datastore v2.
I took a look at the output of this project and it runs quickly and the output is very neatly formatted.

However for the Datastore v2 we use `SDRs per currency unit for national currency`, from [this imf source](https://www.imf.org/external/np/fin/ert/GUI/Pages/Report.aspx?Type=XML&CU=%27EUR%27,%27JPY%27,%27GBP%27,%27USD%27,%27DZD%27,%27AUD%27,%27ATS%27,%27BHD%27,%27BEF%27,%27VEF%27,%27BWP%27,%27BRL%27,%27BND%27,%27CAD%27,%27CLP%27,%27CNY%27,%27COP%27,%27CYP%27,%27CZK%27,%27DKK%27,%27DEM%27,%27FIM%27,%27FRF%27,%27GRD%27,%27HUF%27,%27ISK%27,%27INR%27,%27IDR%27,%27IRR%27,%27IEP%27,%27ILS%27,%27ITL%27,%27KZT%27,%27KRW%27,%27EEK%27,%27KWD%27,%27LYD%27,%27LUF%27,%27MYR%27,%27MTL%27,%27MUR%27,%27MXN%27,%27NPR%27,%27NLG%27,%27NZD%27,%27NOK%27,%27PEN%27,%27PKR%27,%27UYU%27,%27PHP%27,%27PLN%27,%27PTE%27,%27QAR%27,%27OMR%27,%27RUB%27,%27SAR%27,%27SGD%27,%27SKK%27,%27SIT%27,%27ZAR%27,%27ESP%27,%27LKR%27,%27SEK%27,%27CHF%27,%27THB%27,%27TTD%27,%27TND%27,%27AED%27,%27VEB%27&EX=SDRC&P=DateRange&CF=UnCompressed&CUF=Period&DS=Ascending&DT=NA).
Poking around in the datasource that you used that would basically equate to 1/`ENSA_XDC_XDR_RATE` [example source](http://dataservices.imf.org/REST/SDMX_JSON.svc/CompactData/IFS/M.NL.ENSA_XDC_XDR_RATE). 
I would argue that the dsv2 would benefit in completeness by using your method of retrieving exchange rates, however we would have to tweak it to handle the SDRs rather than direct conversion to USD, as we also use this to convert to other currencies.

The question is then, do you have any plans to either expand this, or possibly add an optional parameter to support other conversion methods?

Thanks,
Sylvan

**Comment by markbrough** [comment]
Hi @sylvanr -- 

Many thanks for this and for your kind comments!

You can see the source for exchange rates here:
https://github.com/codeforIATI/imf-exchangerates/blob/828eef65601be208632eeb212b9eea2a60550201/imf-currencies.py#L18-L19

`COUNTRY_URL` is the rate used to convert each country's currency to USD. `XDR_URL` is the rate used to convert XDR to USD.

The `ENSA_` rates are period averages whereas `ENDE_` rates are the rate at the end of the period. I thought that `ENDE` would be a better fit here given that a particular date (the last day of the month) is stated for each exchange rate.

I think it could be useful to make the same rates available against XDR rather than against USD. I don't have time to do this right now, but would welcome a PR if you would like to do so!

I guess the way I would do this is:
* wrap most of the code in a function that takes a parameter e.g. `target` which defaults to USD but can be set to XDR.
* depending on this parameter, collect either USD or XDR rates
* depending on this parameter, output to the existing file `imf_exchangerates.csv` (for USD) or a new file, e.g. `imf_exchangerates_xdr.csv` (for XDR)
* allow specifying this optional parameter on the command line (preferably with [Click](https://pypi.org/project/click/))
* below the following line:
  https://github.com/codeforIATI/imf-exchangerates/blob/828eef65601be208632eeb212b9eea2a60550201/.github/workflows/pythonapp.yml#L27
  add a new line:
  ```bash
  python imf-currencies.py XDR
  ```

**Comment by sylvanr** [comment]
Hi @markbrough, thanks for the reply! 

Regarding the fit, it makes total sense, I think everyone that would use this would have a very specific use case. Expanding on the code for a more generic approach would definitely be handy. 

I've already done some experiments to see if I could use the code to achieve our goals, which is definitely possible! I will follow up with a PR soon. Thanks for the approach tips (especially Click), very handy!
